### ISSUE TITLE
mPaceline

### ISSUE THREAD

**Issue by Appelg** [hypermoose/Keiser2Zwift#3]
The app mPaceline doesn't find any sensor. Zwift works.

Mpaceline seems to work with the official converter.

Any idea on how to troubleshoot?

**Comment by djwasser** [comment]
@Appelg -- I went through the code and cycling-power-service.js uses a UUID of "1515" for cycling power which is not standard.  The current [BLE specification](https://btprodspecificationrefs.blob.core.windows.net/assigned-values/16-bit%20UUID%20Numbers%20Document.pdf) allocates UUID "1818" for Cycling Power.  The code, which appears to trace back to KettlerUSB2BLE: [https://github.com/360manu/kettlerUSB2BLE](https://github.com/360manu/kettlerUSB2BLE), has "1818" commented out, so I am guessing this was some sort of workaround for Kettler that was just carried forward into this project.  (Perhaps @hypermoose can confirm?).

In any case, I modified my copy of cycling-power-service.js to use "1818" as the UUID and reenabled and started the service.  All still works perfectly with Zwift, so apparently no harm there.  I do not use mPaceline, so I did not test with mPaceline to see if it made a difference.  I did use a bluetooth sniffer app on my iPhione (LightBlue) and it now sees the service correctly as "Cyclng Power" whereas before it just reported it as "UUID: 1515".  So my hope is that any application looking for BLE Cycling Power will find the service.  Hope this helps!!

**Comment by Appelg** [comment]
@djwasser yes! It worked! Thanks a lot, really appreciate it! Will you PR, since it's your fix?

**Comment by hypermoose** [comment]
@djwasser Great debugging.  I can make the change so others benefit if you like or if you want to do a PR I will approve it.  You are correct, its just carryover from the Kettler project that I did not double check the UUIDs.

**Comment by djwasser** [comment]
@hypermoose  - please go ahead and do PR.  I am pretty much a github novice  ;-)
And by the way -- this app is great!!!  Really appreciate you making it available.

**Comment by hypermoose** [comment]
@djwasser I've merged the PR and added a comment for the multiple adapters at boot time issues on the Readme.  Thanks to you and @Appelg for making the project better.
