### ISSUE TITLE
Bluetooth bridge works with iPad but not on new lenovo m90t IoT PC

### ISSUE THREAD

**Issue by robcalm** [hypermoose/Keiser2Zwift#5]
Hi There,

Great little tool!  Thanks so much for building it, and the recent fixes which have helped.

I am running on a RPi 3B+ with the zexmte BT adapter.

I originally got this up and running with an ipad and managed to make it work with Zwift, Rouvy and Fulgaz.  It still works on iPad currently.

But I wanted to free myself from the iPad and decided to go to a pc with large monitor rather than a screen adapter for the iPad or appleTV.  I went with this lenovo unit which I found for cheap...

https://www.lenovo.com/ca/en/desktops-and-all-in-ones/thinkcentre/m-nano-series/ThinkCentre-M90n-IoT/p/thinkcentre-m90n-iot

it has an intel bluetooth adapter build in.

My issue is, although the PC can see the keiser bridge (I assume it is the bridge and not just the keiser console computer itself), and Zwift, Rouvy and Fulgaz can see it as well, they don't receive any data.  I've done all the recent fixes in the issues register here, and everything else I can think of to fix this, but have run out of ideas.

One thing I've noticed is that there are these 'unknown devices' popping in and out from the windows 10 bluetooth settings screen, which I can't connect to.  Any chance that the PC bluetooth is somehow  breaking out the main signal into the keiser subcomponents (rpm, power etc) and the apps can't collect it?

What information can I provide that may help one of you knowledgeable types find the cause of this problem?

Thanks!
Rob

**Comment by hypermoose** [comment]
@robcalm I’ve actually seen this on Windows PCs too.   Now that I know that its blocking other users I will try to debug this and let you know what I find.  I suspect something in the connection sequence from Windows is failing and aborting the rest.  Maybe an unexpected response.

**Comment by robcalm** [comment]
Thanks!  Really appreciate the effort.

**Comment by robcalm** [comment]
One other thing that may be related and possibly useful for your debugging efforts.  Even on the iPad, if I kill all the pairings and start fresh then Fulgaz will only find the bridge if I have already found and connected to it via Zwift first.  After that Fulgaz will always find it.

**Comment by robcalm** [comment]
Hi Gary,  I'm wondering whether you've had any time to look into this.  Anything I can do to help?

**Comment by hypermoose** [comment]
Hi @robcalm I have been looking into it but unfortunately haven’t found the problem quite yet.  Sorry its taking so long.  I will reach out when I find something

**Comment by robcalm** [comment]
Thanks Gary.  Don't be sorry... sometimes these things are tricky.

**Comment by hypermoose** [comment]
Hi @robcalm, I think I may have found the issue.  I have a PR out for it.  Could you please try it and let me know if it fixes your issue as well before I merge.  Its branch hypermoose/windows.   Please let me know how it goes

**Comment by robcalm** [comment]
Hi Gary,  I'll give it a try and let you know how it goes

**Comment by robcalm** [comment]
I’m a git noob.  Can you confirm how I build from the current state?  

Something like this?

git checkout master
git pull
npm run build

or does it need to be something more like this?

git master checkout
git fetch origin pull/11/head:hypermoose/windows
git checkout hypermoose/windows
npm run build

**Comment by hypermoose** [comment]
git pull
git checkout hypermoose/windows
npm install
npm start

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by robcalm** [comment]
I ran the build and unfortunately there was no change in the behaviour of BT on the PC side.

So I tried a little trick in RP of requesting a BT connection between the RP broadcast adapter and the PC using the PC's BT adapter MAC address.  The result was that the RP broadcast adapter is listed as paired in windows BT management app.  And strangely, shows as connected intermittently when the keiser bridge is running on the RP.

In Fulgaz, during configuration it can see the Keiser power and cadence adapters and allows you to select them.  However, it doesn't receive data - whether you're pedaling or not it only shows 0 watts and 0 RPM.

Maybe we're getting closer??

**Comment by hypermoose** [comment]
Hmm, let me try Fulgaz on my PC and I will get back to you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by hypermoose** [comment]
I just tried Fulgaz with my new branch by connecting the power and cadence senor.  On the connection page it shows 0 but once you start a ride it works.  I did notice that Fulgaz does not disconnect properly between runs so I had to stop and start npm.  Can you try again?

**Comment by robcalm** [comment]
Yes, I'll retry and report back.  Might take a day or so.

**Comment by robcalm** [comment]
Hi Gary,  I got back to this tonight and your new build works for me.  I have no idea what changed between this try and the last one... I did muck around with a lot of settings.  Sorry for sending you on a goose chase.

Nice job, thanks for taking the time to look at this issue.  Will you add this to your master and close the ticket?

**Comment by hypermoose** [comment]
@robcalm done and done.  Let me know if you see anything else
